/**
 * This code generated by CodeGenerator<320132929@qq.com>
 */
package com.mellower.page.address;

import java.math.BigDecimal;
import java.sql.Date;

/**
 * <p>PageBean类</p>
 * <p>Table: t_address - </p>
 *
 * @since 2017-06-29 06:23:52
 */
public class AddressPage {

	private static final long serialVersionUID = 1L;

    /** id -  */
    private Integer id;

    /** name - 名称 */
   
    private String name;

    /** tel -  */
   
    private String tel;

    /** address -  */
   
    private String address;

    /** remark -  */
   
    private String remark;

    /** user_id -  */
   
    private Integer userId;

    public Integer getId(){
        return this.id;
    }
    public void setId(Integer id){
        this.id = id;
    }

    public String getName(){
        return this.name;
    }
    public void setName(String name){
        this.name = name;
    }

    public String getTel(){
        return this.tel;
    }
    public void setTel(String tel){
        this.tel = tel;
    }

    public String getAddress(){
        return this.address;
    }
    public void setAddress(String address){
        this.address = address;
    }

    public String getRemark(){
        return this.remark;
    }
    public void setRemark(String remark){
        this.remark = remark;
    }

    public Integer getUserId(){
        return this.userId;
    }
    public void setUserId(Integer userId){
        this.userId = userId;
    }
}
