/**
 * This code generated by CodeGenerator<320132929@qq.com>
 */
package com.mellower.repository.address;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jy.repository.base.BaseDao;
import com.jy.repository.base.JYBatis;
import com.mellower.entity.address.Address;
import com.mellower.entity.address.AddressExample;
@JYBatis
public interface AddressMapper extends BaseDao<Address> {
	long countByExample(AddressExample example);

    int deleteByPrimaryKey(Integer fid);

    void insert(Address record);

    int insertSelective(Address record);

    List<Address> selectByExample(AddressExample example);

    Address selectByPrimaryKey(Integer fid);

    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressExample example);

    int updateByExample(@Param("record") Address record, @Param("example") AddressExample example);

    int updateByPrimaryKeySelective(Address record);

    int updateByPrimaryKey(Address record);
}
