/**
 * This code generated by CodeGenerator<320132929@qq.com>
 */
package com.mellower.entity.address;

import org.apache.ibatis.type.Alias;

import com.jy.entity.base.BaseEntity;

import java.math.BigDecimal;
import java.sql.Date;

/**
 * <p>Entity大数类</p>
 * <p>Table: t_address - </p>
 *
 * @since 2017-06-29 06:23:52
 */
@Alias("AddressWithBLOBs")
public class AddressWithBLOBs extends Address {

}
