/**
 * This code generated by CodeGenerator<320132929@qq.com>
 */
package com.mellower.service.address;

import java.util.List;
import java.util.Map;

import com.jy.common.mybatis.Page;
import com.jy.service.base.BaseService;
import com.mellower.entity.address.Address;
import com.mellower.entity.address.AddressExample;
import com.mellower.entity.address.AddressWithBLOBs;

import net.sf.json.JSONObject;

/**
 * <p>服务接口</p>
 * <p>Table: t_address - </p>
 *
 * @since 2017-06-29 06:23:52
 */
public interface AddressService extends BaseService<Address> {
	
	/**
	 * @description 插入或更新
	 * @retrun
	*/
	public Integer saveOrUpdate(AddressWithBLOBs entity);
	
	/**
	 * @description 分页查询 
	 * @return Address<L>
	 */
	public Page<Address> findByPage(Address o, Page<Address> page);
	
	
	/**
	 * @description ID查询
	*/
	public Address findById(Integer id);
	
	/**
	 * @description 选择性插入
	*/
	int saveSelective(Address record);
	
	/**
	 * @description 选择性查询
	*/
	public List<Address> findByExample(AddressExample example);
	
	/**
	 * @description 选择性查询
	*/
	public int updateByIdSelective(Address record);
	
	/**
	 * @description ID删除
	*/
	public int deleteById(Integer id);
	
	@Override
	public void afterdeploy();
	
}
