/**
 * This code generated by CodeGenerator<320132929@qq.com>
 */
package com.mellower.controller.address;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.ServletRequestDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.jy.common.ajax.AjaxRes;
import com.jy.common.mybatis.Page;
import com.jy.common.utils.base.Const;
import com.jy.controller.base.BaseController;
import com.jy.interceptor.core.DateConvertEditor;
import com.mellower.common.utils.JavaNSUnixTimeFormat;
import com.mellower.common.utils.MarsBeanUtils;
import com.mellower.entity.address.Address;
import com.mellower.entity.address.AddressWithBLOBs;
import com.mellower.service.address.AddressService;

/**
 * <p>Controller类</p>
 * <p>Table: t_address - </p>
 *
 * @since 2017-06-29 06:23:52
 */

@Controller
@RequestMapping("/backstage/address/")
public class AddressController extends BaseController<Address> {
	/**
	 * 将前台传递过来的日期格式的字符串，自动转化为Date类型
	 * 
	 * @param binder
	 */
	@InitBinder
	public void initBinder(ServletRequestDataBinder binder) {
		binder.registerCustomEditor(Date.class, new DateConvertEditor());
	}


	@Autowired
	private AddressService addressService;

	/**
	 * @Description: 菜单入口
	 * @since 2017-06-29 06:23:52
	 */
	@RequestMapping("index")
	public String themeIndex(Model model) {
		 if (doSecurityIntercept(Const.RESOURCES_TYPE_MENU)) {
		 model.addAttribute("permitBtn",
		 getPermitBtn(Const.RESOURCES_TYPE_FUNCTION));
			return "/mellower/address/address/list";
		 }
		 return Const.NO_AUTHORIZED_URL;
	}

	/**
	 * @Description: 分页查询
	 * @since 2017-06-29 06:23:52
	 */
	@RequestMapping(value = "findByPage", method = RequestMethod.POST)
	@ResponseBody
	public AjaxRes findByPage(Page<Address> page, Address o) {
		AjaxRes ar = getAjaxRes();
		if (ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_MENU, "/backstage/address/index"))) {
			try {
				Page<Address> list = addressService.findByPage(o, page);
				Map<String, Object> p = new HashMap<String, Object>();
				p.put("permitBtn", getPermitBtn(Const.RESOURCES_TYPE_BUTTON));
				p.put("list", list);
				ar.setSucceed(p);
			} catch (Exception e) {
				logger.error(e.toString(), e);
				ar.setFailMsg(Const.DATA_FAIL);
			}
		}
		return ar;

	}

	/**
	 * @Description: 查询详情
	 * @since 2017-06-29 06:23:52
	 */
	@RequestMapping(value = "find", method = RequestMethod.POST)
	@ResponseBody
	public AjaxRes find(Address entity) {
		AjaxRes ar = getAjaxRes();
		if (ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_BUTTON))) {
			try {
				Address o = addressService.findById(entity.getId());
				ar.setSucceed(o);
			} catch (Exception e) {
				logger.error(e.toString(), e);
				ar.setFailMsg(Const.DATA_FAIL);
			}
		}
		return ar;
	}
	
	@RequestMapping(value="add", method=RequestMethod.POST)
	@ResponseBody
	public AjaxRes add(AddressWithBLOBs wbs){
		AjaxRes ar=getAjaxRes();
		if(ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_FUNCTION))){			
			try {
				addressService.saveOrUpdate(wbs);
				ar.setSucceedMsg(Const.SAVE_SUCCEED);
			} catch (Exception e) {
				logger.error(e.toString(),e);
				ar.setFailMsg(Const.SAVE_FAIL);
			}
		}
		return ar;
	}
	
	@RequestMapping(value="update", method=RequestMethod.POST)
	@ResponseBody
	public AjaxRes update(AddressWithBLOBs wbs){
		AjaxRes ar=getAjaxRes();
		if(ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_BUTTON))){
			try {
				addressService.saveOrUpdate(wbs);
				ar.setSucceedMsg(Const.SAVE_SUCCEED);
			} catch (Exception e) {
				logger.error(e.toString(),e);
				ar.setFailMsg(Const.UPDATE_FAIL);
			}
		}	
		return ar;
	}

	/**
	 * @Description: 实体更新
	 * @since 2017-06-29 06:23:52
	 */
	@RequestMapping(value="addOrUpdate", method=RequestMethod.POST)
	@ResponseBody
	public AjaxRes addOrUpdate(AddressWithBLOBs wbs){
		AjaxRes ar=getAjaxRes();
		if(ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_FUNCTION))){
			try {
				
				addressService.saveOrUpdate(wbs);
				ar.setSucceedMsg(Const.UPDATE_SUCCEED);
			} catch (Exception e) {
				logger.error(e.toString(),e);
				ar.setFailMsg(Const.UPDATE_FAIL);
			}
		}	
		return ar;
	}
	
	/**
	 * @Description: 实体删除
	 * @since 2017-06-29 06:23:52
	 */
	@RequestMapping(value="del", method=RequestMethod.POST)
	@ResponseBody
	public AjaxRes del(Address entity){
		AjaxRes ar=getAjaxRes();
		if(ar.setNoAuth(doSecurityIntercept(Const.RESOURCES_TYPE_BUTTON))){
			try {
				
				addressService.deleteById(entity.getId());
				ar.setSucceedMsg(Const.DEL_SUCCEED);
			} catch (Exception e) {
				logger.error(e.toString(),e);
				ar.setFailMsg(Const.DEL_FAIL);
			}
		}	
		return ar;
	}
	
}
